# Generated by Django 4.2.4 on 2023-08-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(help_text='Max 30 character', max_length=30),
        ),
        migrations.AlterField(
            model_name='chassis',
            name='number',
            field=models.CharField(help_text='Max 16 digits', max_length=16),
        ),
    ]
